echo "Arguments total: $#"
echo "script name: $0"
echo "scripts 1st Argument : $1"
echo "scripts 2nd Argument : $2"
echo "scripts 3rd Argument : $3"
echo "List of all arguments: * $*"
echo "List of all Arguments: @ $@"
echo "PID of shell:$$"
